### ISSUE TITLE
Outline package details in README.md

### ISSUE THREAD

**Issue by yaz-saleh** [UBC-MDS/pymleda#7]
- [ ] a summary paragraph that describes the project at a high level

- [ ] a bulleted list of the functions (and datasets if applicable) that will be included in the package (this should be a 1-2 sentence description for each function/dataset)

- [ ] a paragraph describing where your packages fit into the Python ecosystem (are there any other Python packages that have the same/similar functionality? Provide links to any that do. If none exist, then clearly state this as well).

**Comment by Saule-Atymtayeva** [comment]
## Features

- [ ] a summary paragraph that describes the project at a high level

- [ ] a bulleted list of the functions (and datasets if applicable) that will be included in the package (this should be a 1-2 sentence description for each function/dataset)

The pymleda package will include the following functions:
-	______ to identify types of variables/ columns in a pandas dataframe
-	`autoimpute_na` to identify and impute missing values in a pandas dataframe
-	______ to split a pandas dataframe into train and test datasets
-	______ to apply simple transformer (scaling , etc.).

- [ ] a paragraph describing where your packages fit into the Python ecosystem (are there any other Python packages that have the same/similar functionality? Provide links to any that do. If none exist, then clearly state this as well)

Since the `pymleda` package will be the part of EDA in supervised machine learning, we believe this package might be useful as a part of the `scikit-learn` library in Python. At the same time, given that our package will work with pandas dataframes, it could also live in the `pandas` library.

As mentioned earlier, there are Python libraries such as [`scikit-learn`](https://scikit-learn.org) and [`pandas`](https://pandas.pydata.org) that contain some similar functionality. For example, `pandas` provide users with separate functions such as `isnull()`, `isna()`, and `notna()` to detect missing values and ` fillna()`, ` interpolate()` to fill them. The `autoimpute_na` function will combine these two steps of identifying and imputing missing values in columns of a dataframe while taking into account the type of these columns (numeric or categorical). Moreover, `autoimpute_na` will detect some common non-standard missing values manually entered by users (e.g., "not available", "n/a", "na", "-"). The output of the `autoimpute_na` function will be a dataframe with imputed values.

**Comment by tanmaysharma19** [comment]
Addressed in #20
